from typing import List
import signal

from routing.entity.instance import Instance
from routing.algorithm.lns import lns
from routing.entity.error import TimeOutException


def time_out_handler(signum, frame):
    raise TimeOutException()


signal.signal(signal.SIGALRM, time_out_handler)


class Policy(object):
    """
    The live dispatching policy.

    A policy is always associated with a single instance and can be used
    to dispatch multiple deliveries into the instance plan.

    Examples
    ```python
    from routing import Instance, Policy

    i = Instance()
    # ... load an instance and add new deliveries

    p = Policy(i)
    p.route()

    # At this point all the deliveries that were not assigned
    # to any job have been dispatched!
    ```
    """

    def __init__(self, instance: Instance):
        """
        Initialize the policy with an instance.
        Args:
            instance: a routing.entity.instance.Instance object
        """
        self.instance = instance

    def route(self, delivery_ids: List[int] = None, resolution_time=None):
        """
        Dispatch the deliveries that are not assigned to any job.
        After the dispatch it updates the plan associated with the instance.

        Note that to stop the computation after the time is expired this function uses signals
        that only works on Unix system and if the thread in charge of the computation is the main
        thread.

        Args:
            delivery_ids: an optional collection of delivery ids that represent the last added deliveries.
            resolution_time: max number of seconds for the computations, if None it uses as much time as needed

        Returns: the solution generated by the algorithm
        """
        if resolution_time is not None:
            signal.alarm(resolution_time)

        try:
            sol = lns(self.instance)
            signal.alarm(0)

            # Update the plan
            for j in sol.jobs:
                sol.compute_job_data(j.id)

                self.instance.plan.set_tasks(job_id=j.id,
                                             route=[(task_id,
                                                     sol.tasks[task_id].arrival_time,
                                                     sol.tasks[task_id].departure_time)
                                                    for task_id in j.task_ids])
        finally:  # Turn off the alarm in case of any exception or end of computation
            signal.alarm(0)
        return sol
