cdef int C_NONE_JOB = -1
cdef int C_NONE_DELIVERY = -1
cdef int C_NONE_TASK = -1
cdef int C_NONE_POSITION = -1
cdef int C_NONE_DELIVERY_GROUP = -1
cdef int C_NONE_TIME = -1

NONE_JOB = C_NONE_JOB
NONE_DELIVERY = C_NONE_DELIVERY
NONE_TASK = C_NONE_TASK
NONE_POSITION = C_NONE_POSITION
NONE_DELIVERY_GROUP = C_NONE_DELIVERY_GROUP
NONE_TIME = C_NONE_TIME